name: penoft_machine_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  email_validator: ^3.0.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  fluttertoast: ^9.0.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  google_sign_in: ^6.2.1
  http: ^1.6.0
  image_picker: ^1.2.1
  lottie: ^3.3.2
  pinput: ^5.0.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.9.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
